Vagrant.configure("2")do|config|
  config.vm.box="b2-tp2-centos"

  config.vbguest.auto_update = false

  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "node1" do |node1|
      node1.vm.hostname = "node1.tp2.b2"
      node1.vm.network "private_network", ip: "192.168.2.21", netmask:"255.255.255.0"
      node1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2.tp2.b2"
    node2.vm.network "private_network", ip: "192.168.2.22", netmask:"255.255.255.0"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end
end